[project]
name = "complex-systems"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.11.0",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "torch>=2.9.0",
    "transformers>=4.57.1",
]
